- hosts: all
  sudo:	True
  user:	vagrant
  tasks:
    - name: "Atualizando pacotes"
      shell: sudo apt-get -y update

    - name: "Instalando git, maven2 e openjdk-6-jdk"    ## ok
      shell: sudo apt-get install -y git maven2 openjdk-6-jdk

    - name: "Clonando o projeto loja-virtual-devops.git"   ## ok
      shell: git clone https://github.com/IBM-Bluemix/todo-apps.git

    - name: "Export MAVEN_OPTS"   
      shell: export MAVEN_OPTS=-Xmx256m   

    - name: "Execução do Maven"   
      shell: sudo mvn -f /home/vagrant/todo-apps/java/bluemix-todo-app/pom.xml

    - name: "Execução do Maven"   
      shell: mvn -P run -f /home/vagrant/tudo-apps/java/bluemix-todo-app/pom.xml





